---
Name: mysite
After: 'framework/*','cms/*, calendar/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'light'

SiteConfig:
  extensions:
   - CustomSiteConfig
DBField:
  extensions:
   - RichLinksExtension
   - PagebreaksExtension
LeftAndMain:
  extra_requirements_css:
   - 'mysite/css/custom.css'
Member:
  extensions:
   - MemberExtension
SecurityAdmin:
  extensions:
   - SecurityAdminExtension
Event:
  extensions:
    - EventExtension

ErrorPage:
  icon: "mysite/images/sitetree_images/error.png"
UserDefinedForm:
  icon: "mysite/images/sitetree_images/form.png"
  extensions:
   - UserDefinedFormExtension
CalendarAdmin:
  menu_icon: "mysite/images/sitetree_images/event.png"
CalendarPage:
  icon: "mysite/images/sitetree_images/event.png"
AddEventPage:
  icon: "mysite/images/sitetree_images/calendar-plus.png"

EventPage:
  icon: "mysite/images/sitetree_images/date-recurring.png"
SubmittedForm:
  extensions:
   - SubmittedFormExtension
KickAssets:
  menu_icon: "mysite/images/sitetree_images/photo.png"
  menu_title: "Files"

FormSpamProtectionExtension:
  default_spam_protector: '\StudioBonito\SilverStripe\SpamProtection\Honeypot\SpamProtector\HoneypotSpamProtector'


LeftAndMain:
  extra_requirements_css:
   - 'app/css/leftandmain.css'
