---
Name: mysite
After: 'framework/*','cms/*, calendar/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'hydra'

SiteConfig:
  extensions:
   - CustomSiteConfig
DBField:
  extensions:
   - RichLinksExtension
   - PagebreaksExtension
LeftAndMain:
  extra_requirements_css:
   - 'mysite/css/custom.css'
Member:
  extensions:
   - MemberExtension
SecurityAdmin:
  extensions:
   - SecurityAdminExtension
Event:
     extensions:
      - EventExtension

ErrorPage:
  icon: "mysite/images/sitetree_images/error.png"
UserDefinedForm:
  icon: "mysite/images/sitetree_images/form.png"
  extensions:
   - UserDefinedFormExtension
CalendarAdmin:
  menu_icon: "mysite/images/sitetree_images/event.png"
CalendarPage:
  icon: "mysite/images/sitetree_images/event.png"
EventPage:
  icon: "mysite/images/sitetree_images/date-recurring.png"
SubmittedForm:
  extensions:
   - SubmittedFormExtension

Link:
  extensions:
   - LinkExtension

FormSpamProtectionExtension:
  default_spam_protector: '\StudioBonito\SilverStripe\SpamProtection\Honeypot\SpamProtector\HoneypotSpamProtector'
